# Generated by Django 2.2.1 on 2019-05-20 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'managed': False},
        ),
    ]
