# Generated by Django 2.2.1 on 2019-05-20 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_name', models.CharField(max_length=45)),
                ('cus_address', models.CharField(max_length=45)),
                ('cus_phone', models.CharField(max_length=45)),
                ('cus_list', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineSell',
            fields=[
                ('line_sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_amount', models.IntegerField()),
                ('sell_breed_price', models.FloatField()),
                ('sell_full_price', models.FloatField()),
                ('sell_date', models.DateField()),
            ],
            options={
                'db_table': 'line_sell',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sell',
            fields=[
                ('sell_id', models.AutoField(primary_key=True, serialize=False)),
                ('sell_sum_amount', models.FloatField()),
                ('sell_sum_price', models.FloatField()),
                ('discount', models.IntegerField()),
                ('discount_price', models.FloatField()),
                ('sell_total_price', models.FloatField()),
            ],
            options={
                'db_table': 'sell',
                'managed': False,
            },
        ),
    ]
