# Generated by Django 2.2.1 on 2019-05-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name_breed', models.CharField(max_length=45)),
                ('type_breed', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='QualityControl',
            fields=[
                ('quality_id', models.AutoField(primary_key=True, serialize=False)),
                ('quality_lot', models.IntegerField()),
                ('quality_date', models.DateField()),
                ('quality_keep_date', models.DateField()),
                ('seed_moistness', models.FloatField()),
                ('seed_germination', models.FloatField()),
                ('seed_strong', models.FloatField()),
                ('quality_weight', models.FloatField()),
                ('quality_check_date', models.FloatField()),
            ],
            options={
                'db_table': 'quality_control',
                'managed': False,
            },
        ),
    ]
