# Generated by Django 2.2.1 on 2019-05-20 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('buy_id', models.AutoField(primary_key=True, serialize=False)),
                ('buy_date', models.DateField()),
                ('buy_weight', models.IntegerField()),
                ('buy_moistness', models.FloatField()),
                ('buy_moistness_cut', models.IntegerField()),
                ('buy_adultrant_seed', models.FloatField()),
                ('buy_adultrant_cut', models.IntegerField()),
                ('buy_other_seed', models.IntegerField()),
                ('buy_iodine', models.IntegerField()),
                ('buy_redrice', models.IntegerField()),
                ('buy_grde', models.CharField(max_length=2)),
                ('buy_total_weight', models.IntegerField()),
                ('buy_cost', models.FloatField()),
                ('buy_total_cost', models.FloatField()),
            ],
            options={
                'db_table': 'buy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('sup_id', models.AutoField(primary_key=True, serialize=False)),
                ('sup_firstname', models.CharField(max_length=45)),
                ('sup_lastname', models.CharField(max_length=45)),
                ('sup_sex', models.CharField(max_length=45)),
                ('sup_address', models.CharField(max_length=45)),
                ('sup_field', models.IntegerField()),
            ],
            options={
                'db_table': 'supplier',
                'managed': False,
            },
        ),
    ]
